// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJWOvNRCmNHn-2M1Wj4D2o7YWSd2wU1Es',
    appId: '1:610643451133:web:9449cf3b91e172aafdf294',
    messagingSenderId: '610643451133',
    projectId: 'brybry-fce98',
    authDomain: 'brybry-fce98.firebaseapp.com',
    storageBucket: 'brybry-fce98.appspot.com',
    measurementId: 'G-QH1X4PQGQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTeoy3_0L3zjytVfqwcL63-jpXUd8SF9g',
    appId: '1:610643451133:android:fcdac9f6d02c28a7fdf294',
    messagingSenderId: '610643451133',
    projectId: 'brybry-fce98',
    storageBucket: 'brybry-fce98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp_vMlMR0GPo-h3h3_35A_Ao22ONLxAys',
    appId: '1:610643451133:ios:1759c54702b2cf85fdf294',
    messagingSenderId: '610643451133',
    projectId: 'brybry-fce98',
    storageBucket: 'brybry-fce98.appspot.com',
    iosBundleId: 'com.example.trialfinalproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp_vMlMR0GPo-h3h3_35A_Ao22ONLxAys',
    appId: '1:610643451133:ios:1759c54702b2cf85fdf294',
    messagingSenderId: '610643451133',
    projectId: 'brybry-fce98',
    storageBucket: 'brybry-fce98.appspot.com',
    iosBundleId: 'com.example.trialfinalproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJWOvNRCmNHn-2M1Wj4D2o7YWSd2wU1Es',
    appId: '1:610643451133:web:9b127c2d7a1e04e4fdf294',
    messagingSenderId: '610643451133',
    projectId: 'brybry-fce98',
    authDomain: 'brybry-fce98.firebaseapp.com',
    storageBucket: 'brybry-fce98.appspot.com',
    measurementId: 'G-Y91DLYGMCE',
  );
}
